### ISSUE TITLE
specify fields to be returned in batch reverse geocoding

### ISSUE THREAD

**Issue by burritojustice** [geocodeearth/ge#6]
It would be helpful to be able to specify which fields are returned when batch geocoding a CSV.

Maybe `-f ge:admin:region,ge:admin:county` ?

**Comment by missinglink** [comment]
What would be the use-case for this?
If it's purely to reduce the output file size I don't feel like it's worth adding this feature.

There are loads of tools out there which can be used to remove any superfluous columns, such as [xsv select](https://github.com/BurntSushi/xsv).

**Comment by burritojustice** [comment]
Makes sense.
